security:
  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  role_hierarchy:
    ROLE_ADMIN: [ROLE_BARBER, ROLE_CLIENT]
    ROLE_BARBER: []
    ROLE_CLIENT: []
    ROLE_USER: []

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider

      form_login:
        login_path: app_login
        check_path: app_login
        success_handler: App\Security\CustomAuthenticationSuccessHandler

      logout:
        path: /logout
        target: /login

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/logout, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/users, roles: ROLE_ADMIN }
    - { path: ^/barber, roles: ROLE_BARBER }
    - { path: ^/client, roles: ROLE_CLIENT }
    - { path: ^/barbershop, roles: ROLE_BARBER }
    - { path: ^/profile, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/about, roles: PUBLIC_ACCESS }
    - { path: ^/$, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
